# Generated by Django 4.1.6 on 2023-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('LC', 'Listing Category'), ('TY', 'Toys'), ('AN', 'Antiques'), ('ME', 'Memorabilia'), ('TO', 'Tools'), ('CA', 'Car Parts'), ('HG', 'Home Goods'), ('FA', 'Fashion'), ('EL', 'Electronics')], default='Listing Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
