# Generated by Django 4.1.6 on 2023-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_category_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('LC', 'Listing Category'), ('TY', 'Toys'), ('AN', 'Antiques'), ('ME', 'Memorabilia'), ('TO', 'Tools'), ('CA', 'Car Parts'), ('HG', 'Home Goods'), ('FA', 'Fashion'), ('EL', 'Electronics')], default='LC', max_length=100),
        ),
    ]
