# Generated by Django 4.1.6 on 2023-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Listing Category', 'Listing Category'), ('Toys', 'Toys'), ('Antiques', 'Antiques'), ('Memorabilia', 'Memorabilia'), ('Tools', 'Tools'), ('Car Parts', 'Car Parts'), ('Home Goods', 'Home Goods'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics')], default='Listing Category', max_length=100),
        ),
    ]
