# Generated by Django 4.1.6 on 2023-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('LC', 'Listing Category'), ('TY', 'Toys'), ('AN', 'Antiques'), ('ME', 'Memorabilia'), ('TO', 'Tools'), ('CA', 'Car Parts'), ('HG', 'Home Goods'), ('FA', 'Fashion'), ('EL', 'Electronics')], default='Listing Category', max_length=40),
        ),
    ]
