# Generated by Django 4.1.6 on 2023-03-19 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_left',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
