# Generated by Django 4.1.6 on 2023-04-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
