# Generated by Django 4.1.6 on 2023-05-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time_left',
        ),
    ]
