# Generated by Django 4.1.6 on 2023-03-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_description_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='static/auctions/Images'),
        ),
    ]
