# Generated by Django 4.1.6 on 2023-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_time_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='created'),
            preserve_default=False,
        ),
    ]
