# Generated by Django 4.1.6 on 2023-03-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
